[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Literature_Analysis"
version = "1"
authors = [
    {name = "Wojciech Socha"}
]
description = "Projekt zaliczeniowy - Narzędzia programistyczne w Pythonie wspierające analizę danych"

dependencies = [

]

[project.optional-dependencies]
test = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]